json.id user.id
json.first_name user.first_name
json.middle_name user.middle_name
json.last_name user.last_name
json.email user.email
json.status user.status
json.is_elected? user.is_elected?
json.is_admin? user.is_admin?
json.created_at user.created_at
json.updated_at user.updated_at
json.association_role_id user.association_role_id
json.property_address_id user.property_address_id
json.action_by_address_user user.action_by_address_users
